# Project information
site_name: Example_doc
site_url: https://github.com/xlavm/Markdown
site_author: Luis Angel Vanegas Martinez
site_description: >-
  Create a documentation of example

# Repository
repo_name: xlavm/Markdown
repo_url: https://github.com/xlavm/Markdown
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 LAVM

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xlavm
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/xlavm
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/xlavm
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/xlavm1/
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCsFxicrm7ysiQk9jZ2WZNtg?view_as=subscriber
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/squidfunk

theme:
    name: material
    locale: es
    features:
      - content.code.copy
      - content.code.annotate
      - content.tabs.link

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


